version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chatstore
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatstore
      - SPRING_DATA_MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mongo-data:
