version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chatstore
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  springboot-app:
    build: .
    container_name: chat-storage-service_app
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/chatstore
    restart: always

volumes:
  mongo-data:
